package tech.tresearchgroup.wrappers.handbrake.model;

import lombok.Data;
import picocli.CommandLine;

@Data
public class GeneralOptions {
    @CommandLine.Option(names = "--help", description = "Print help")
    private boolean help;

    @CommandLine.Option(names = "--version", description = "Print version")
    private boolean version;

    @CommandLine.Option(names = "--json", description = "Log title, progress, and version info in. JSON format")
    private boolean json;

    @CommandLine.Option(names = "--verbose", description = "Be verbose (optional argument: logging level)")
    private String verbose;

    @CommandLine.Option(names = "--preset", description = "Select preset by name (case-sensitive). Enclose names containing spaces in double quotation marks (e.g. \"Preset Name\")")
    private String preset;

    @CommandLine.Option(names = "--preset-list", description = "List available presets")
    private boolean presetList;

    @CommandLine.Option(names = "--preset-import-file", description = "Import presets from a json preset file. 'filespec' may be a list of files separated by spaces, or it may use shell wildcards.")
    private String presetImportFile;

    @CommandLine.Option(names = "--preset-import-gui", description = "Import presets from GUI config preset file.")
    private boolean presetImportGui;

    @CommandLine.Option(names = "--preset-export", description = "Create a new preset from command line options and write a json representation of the preset to the console or a file if '--preset-export-file' is specified. The required argument will be the name of the new preset.")
    private String presetExport;

    @CommandLine.Option(names = "--preset-export-file", description = "Write new preset generated by '--preset-export' to file 'filename'.")
    private String presetExportFile;

    @CommandLine.Option(names = "--preset-export-description", description = "Add a description to the new preset created with '--preset-export'")
    private String presetExportDescription;

    @CommandLine.Option(names = "--queue-import-file", description = "Import an encode queue file created by the GUI")
    private String queueImportFile;

    @CommandLine.Option(names = "--no-dvdnav", description = "Do not use dvdnav for reading DVDs")
    private String noDvdnav;
}
